USE [BDAGENDAMENTO]
GO

/****** Object:  Table [dbo].[AGENDAMENTO]    Script Date: 03/31/2016 17:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AGENDAMENTO](
	[COD] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[HORARIO] [time](7) NOT NULL,
	[NOME] [nvarchar](25) NOT NULL,
	[TELEFONE] [nvarchar](16) NOT NULL,
	[STATUS] [nvarchar](12) NOT NULL,
 CONSTRAINT [PK_AGENDAMENTO] PRIMARY KEY CLUSTERED 
(
	[COD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


